### ISSUE TITLE
Versión Raspbian - arm32v7

### ISSUE THREAD

**Issue by bepece1** [tzinm/descargas-bcpt#1]
Hola,
Me parece una genial idea "descargas-bcpt" pero no me funciona en en mi raspberry bajo raspbian

¿podríais crear un tags con una versión válida para raspbian? Seria genial 🥇 

No obstante, muchas gracias  por todo.

**Comment by tzinm** [comment]
Hola, sí, actualmente sólo se encuentra la versión para arquitecturas de 64 bits. Me lo anoto y en cuanto saque algo de tiempo me pongo manos a la obra.

Un saludo!

**Comment by bepece1** [comment]
Hola @tzinm veo que has hecho avances para la arquitectura "arm"
Veo que en la documentacion hablas de que en docker se puede seleccionar la arquitectura "arm" pero no está subido el "tag" al github de docker.
Yo por mi cuenta he intentado usar el Dockerfile que has creado para arm pero me da varios errores.

Ya me comentas e igualmente me ofrezco para ser el beta tester.

Gracias.

**Comment by tzinm** [comment]
Sí, hace unas semanas estuve haciendo varias pruebas y cree la rama para empezar con las pruebas para adaptar el contenedor a la arquitectura arm.

No conseguí que funcionase, me ha dado bastantes errores y he intentado corregir estos modificando el script de Python que es el que permite reenviar los torrentes a través de Telegram.

Esto lo hice hace unas semanas, he estado un poco ocupado y probablemente hasta navidades no pueda sentarme a mirarlo con calma.

De todos modos, cualquier novedad que haya lo comentaré por aquí.

P.D.: te agradezco que te ofrezcas como betatester, pero de momento es más sencillo que vaya haciendo la pruebas de forma local.

Un saludo :)

**Comment by tzinm** [comment]
Versión disponible para **arm32v7**, para descargar la versión simplemente hay que cambiar **latest** por **arm32v7**.

**Comment by bepece1** [comment]
> Versión disponible para **arm32v7**, para descargar la versión simplemente hay que cambiar **latest** por **arm32v7**.

Funcionando perfectamente en raspbian
