### ISSUE TITLE
Varios usuarios permitidos

### ISSUE THREAD

**Issue by Uriel6** [tzinm/descargas-bcpt#2]
Estoy usando el bot en una raspberry pi, y queria saber si se podrian pasar mas de 1 id de usuario telegram para enviarle archivos al mismo bot. 
Me lo imaginaba como variables de entorno, usuario2 y usuario3 por ejemplo.

**Comment by tzinm** [comment]
Hola!

En principio se puede implementar, de hecho en el script de Python [original](https://github.com/alfilesnet/telegram/blob/master/AddToQbitTorrentFolder.py) está implementado, pero hay que añadir cada usuario de forma manual.

Para incluirlo en el contenedor mi idea es que se puedan añadir a través de variables de entorno, tal y como has puesto de ejemplo. Para ello es necesario hacer ciertas modificaciones en el script.

Ya que has abierto este "issue", aprovecho para dejarlo como referencia para añadir esta nueva funcionalidad.

**Comment by tzinm** [comment]
@Uriel6 he realizado las modificaciones correspondientes al script de Python para que se le puedan añadir tantos usuarios/grupos como se desee. De momento el script está disponible en la rama [dev](https://github.com/tzinm/descargas-bcpt/tree/dev) (por si quieres probarlo). 

Mañana (espero que me de tiempo), lo pondré en producción.

Si te animas a probarlo, para que detecte correctamente tanto los usuarios como los grupos estos tienen que renombrarse correlativamente, es decir:

**Para usuarios:**

* usuario1
* usuario2
* usuario3
* ...

**Para grupos:**

* grupo1
* grupo2
* grupo3
* ...

**Comment by Uriel6** [comment]
Barbaro, gracias.

**Comment by tzinm** [comment]
> Barbaro, gracias.

Ya está disponible para descargar desde Docker Hub.
